export const siteConfig = {
  name: "Hingula Vidya Pitha",
  shortName: "HVP",
  domain: "hingula-vidyapitha.lovable.app",
  description:
    "Government aided high school under Board of Secondary Education, Odisha. Established in 1992, providing quality education in Bhotaka, Kuakhia, Jajpur district.",
  keywords: [
    "school",
    "education",
    "BSE Odisha",
    "government school",
    "aided school",
    "Jajpur",
    "Bhotaka",
    "Kuakhia",
    "high school",
    "NCC",
    "Eco Club",
    "Energy Club",
    "Hingula Vidya Pitha",
  ],
  author: {
    name: "Hingula Vidya Pitha",
    email: "hingulavidyapitha@gmail.com",
    phone: "8260191483",
  },
  established: 1992,
  affiliation: "Board of Secondary Education, Odisha",
  motto: "विद्या ददाति विनयम् — Knowledge bestows humility",
  location: {
    address: "AT/PO-Bhotaka, Kuakhia",
    district: "Jajpur",
    state: "Odisha",
    pincode: "755026",
    country: "India",
  },
  social: {
    youtube: "https://www.youtube.com/channel/UCObdFVD75nivRmynUrLRutg",
    whatsapp: "918260191483",
    facebook: "",
    twitter: "",
    instagram: "",
  },
  contact: {
    phone: "8260191483",
    email: "hingulavidyapitha@gmail.com",
    officeHours: "Mon–Sat · 09:30 – 16:00",
  },
  academics: {
    classes: "Class VIII to X",
    board: "BSE Odisha",
    medium: "Odia, English",
  },
  features: {
    hasNCC: true,
    hasEcoClub: true,
    hasEnergyClub: true,
    hasLibrary: true,
    hasScienceLab: true,
    hasSportsGround: true,
  },
  stats: {
    students: 125,
    faculty: 9,
    passRate: 100,
    yearsOfLegacy: 34,
  },
};

export type SiteConfig = typeof siteConfig;
